name: Flutter APK Build

on:
  workflow_dispatch:

# GitHub ke naye platform updates ko support karne ke liye settings
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Latest Node 24 compatible Checkout standard
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Latest Java Setup plugin (Temurin distribution ke sath)
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Stable Flutter Action framework
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # 4. Project ki saari dependencies fetch karna
      - name: Install Dependencies
        run: |
          cd play_app
          flutter pub get

      # 5. Production Release APK compile karna
      - name: Build APK Release
        run: |
          cd play_app
          flutter build apk --release

      # 6. Final APK ko download ke liye ready karna
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: play_app/build/app/outputs/flutter-apk/app-release.apk
          
